stages:
  - build
  - test
  - scan
  - push
  - update-manifest

image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    command: ["--insecure-registry=host.docker.internal:8082"]


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  NEXUS_REGISTRY: "host.docker.internal:8082"
  IMAGE_NAME: "$NEXUS_REGISTRY/devops-dummy-api"

build:
  stage: build
  script:
    - export IMAGE_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - cd api
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker save -o ../image.tar $IMAGE_NAME:$IMAGE_TAG
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour

test:
  stage: test
  image: node:20-alpine
  services:
    - name: postgres:16-alpine
      alias: postgres
  variables:
    POSTGRES_USER: devops
    POSTGRES_PASSWORD: devops
    POSTGRES_DB: devops_app
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_USER: devops
    DB_PASSWORD: devops
    DB_NAME: devops_app
  before_script:
    - apk add --no-cache postgresql-client
    - PGPASSWORD=devops psql -h postgres -U devops -d devops_app -f "$CI_PROJECT_DIR/db/init.sql"
  script:
    - cd api
    - npm install
    - npm test

scan:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --input image.tar --severity HIGH,CRITICAL --exit-code 1 --ignorefile .trivyignore

push:
  stage: push
  script:
    - export IMAGE_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - docker load -i image.tar
    - echo "$NEXUS_PASS" | docker login $NEXUS_REGISTRY -u "$NEXUS_USER" --password-stdin
    - docker push $IMAGE_NAME:$IMAGE_TAG

update-manifest:
  stage: update-manifest
  script:
    - export IMAGE_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - apk add --no-cache git sed
    - git config user.email "ci@devops-app.local"
    - git config user.name "GitLab CI"
    - git remote set-url origin "https://oauth2:${GITLAB_PUSH_TOKEN}@gitlab.com/ahmedsalem.me.as/sre.git"
    - 'sed -i "s/tag: .*/tag: \"$IMAGE_TAG\"/" k8s/devops-api-chart/values.yaml'
    - git add k8s/devops-api-chart/values.yaml
    - 'git commit -m "ci: bump devops-api image tag to $IMAGE_TAG [skip ci]" || echo "No changes to commit"'
    - git push origin HEAD:main