sonar.projectKey=devops-sre-app
sonar.projectName=DevOps SRE Dummy App
sonar.sources=api/src,worker/src
sonar.exclusions=**/node_modules/**    //without it, SonarQube would try to analyze every file it finds — including anything under node_modules
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=api/coverage/lcov.info

