apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-limits-and-no-latest-tag
spec:
  validationFailureAction: Enforce            # Enforce the policy and block non-compliant resources
  background: true
  rules:
    - name: require-resource-limits           # Require CPU and memory resource limits for all containers in a Pod
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:                # Exclude the argocd namespace from this rule
        any:
          - resources:
              namespaces:
                - argocd
                - argo-rollouts
      validate:
        message: "Every container must set CPU and memory resource limits."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
                    memory: "?*"
    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - argocd
                - argo-rollouts
      validate:
        message: "Image tag ':latest' is forbidden — use a specific version tag."
        pattern:
          spec:
            containers:
              - image: "!*:latest"