image:
  repository: host.docker.internal:8082/devops-dummy-api
  tag: "ce3939da"

replicaCount: 3

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

hpa:
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50

db:
  host: "host.docker.internal"
  port: "5432"
  name: "devops_app"
  user: "devops"
  password: "devops"